### ISSUE TITLE
Only single instance multi-models handled

### ISSUE THREAD

**Issue by richardpayne** [into-cps/INTO-CPS_Application#11] opened 2016-03-29 10:04 UTC
The COE does not handle multiple instances of a FMU properly:

e.g. <guid>.instance1 and <guid>.instance2 does not work correctly

**Comment by CThuleHansen** [comment] 2016-04-04 10:10
Do you have any examples of this, so I can reproduce it?

**Comment by richardpayne** [comment] 2016-04-04 10:18
This was the issue raised by Carl, regarding the COE not handling multi-process instantiation. Carl added an example here:

https://dl.dropboxusercontent.com/u/14852535/2sensorTestWithSDPs.zip

**Comment by CThuleHansen** [comment] 2016-04-04 11:26
Ah okay. Then I understand.

For future reference:
This issue concerns using the same FMU for multiple instances.
Normally this is not an issue, but in this case the FMU in question contains the following flag: canBeInstantiatedOnlyOncePerProcess="true". It is preferable, that the FMUs themselves offer the ability to create separate instances. I guess the reason for not doing this is, that the implementation uses global variables.

However, looking at comment below from the generated source files it looks like it will be possible to export FMUs from 20-sim later on, where multiple instances can be spawned.
`/* only one static instance for now */`
Otherwise it might be possible to load multiple instances by copying and renaming the dll.

**Comment by CThuleHansen** [comment] 2016-04-04 11:31
This seems to have been fixed in 20-sim 4-days ago: https://github.com/controllab/fmi-export-20sim/commit/65b8dfed9b413ac16c99fea1a9a354500063360d

**Comment by CThuleHansen** [comment] 2016-04-05 08:02
Unfortunately the commit has been reverted. 
https://github.com/controllab/fmi-export-20sim/commit/65b8dfed9b413ac16c99fea1a9a354500063360d

**Comment by CThuleHansen** [comment] 2016-04-05 08:08
Todo:
Check if canBeInstantiatedOnlyOncePerProcess="true" and if so, then return an error detailing, that it is not supported currently.

**Comment by CThuleHansen** [comment] 2016-04-05 09:51
I have converted this into #17, and a commit returning a better error is on the way.

**Closed** 2016-04-06 05:34 UTC
Labels: enhancement
